[colors.primary]
# background = "#191724"
background = "#000000"
foreground = "#e0def4"

[colors.normal]
black = "#26233a"
blue = "#9ccfd8"
cyan = "#ebbcba"
green = "#31748f"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[colors.bright]
black = "#6e6a86"
blue = "#9ccfd8"
cyan = "#ebbcba"
green = "#31748f"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
opacity = 0.80

[window.dimensions]
columns = 80
lines = 24

# [window.padding]
# x = 5
# y = 5
