icons_format = "{icon}"

[theme]
theme = "slick"

[icons]
icons = "awesome6"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"
format = "$icon $utilization"
interval = 1

[[block]]
block = "disk_space"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $used / $available"

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:4,u:B,p:G) / $mem_avail.eng(w:4,u:B,p:G)"
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d.%m.%y %R') "
