# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, D, Launch apps, exec, omarchy-launch-walker
bindd = SUPER ALT, D, Omarchy Menu, exec, omarchy-menu

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server
bindd = SUPER SHIFT, Q, Close window, killactive
# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
unbind = SUPER, SPACE
unbind = SUPER, J
unbind = SUPER, P
unbind = SUPER, L
unbind = SUPER, O
unbind = SUPER, Space
unbind = SUPER ALT, Space
#bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
