[colors.bright]
black = "#6e6a86"
blue = "#9ccfd8"
cyan = "#ebbcba"
green = "#31748f"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[colors.cursor]
cursor = "#524f67"
text = "#e0def4"

[colors.dim]
black = "#6e6a86"
blue = "#9ccfd8"
cyan = "#ebbcba"
green = "#31748f"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[colors.footer_bar]
background = "#1f1d2e"
foreground = "#e0def4"

[colors.hints.end]
background = "#1f1d2e"
foreground = "#6e6a86"

[colors.hints.start]
background = "#1f1d2e"
foreground = "#908caa"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#26233a"
blue = "#9ccfd8"
cyan = "#ebbcba"
green = "#31748f"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[colors.primary]
background = "#191724"
bright_foreground = "#e0def4"
dim_foreground = "#908caa"
foreground = "#e0def4"

[colors.search.focused_match]
background = "#ebbcba"
foreground = "#191724"

[colors.search.matches]
background = "#26233a"
foreground = "#908caa"

[colors.selection]
background = "#403d52"
text = "#e0def4"

[colors.vi_mode_cursor]
cursor = "#524f67"
text = "#e0def4"

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
opacity = 0.93
title = "Alacritty"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 5
y = 5
